### PR TITLE
added pending to teams

### LINKED ISSUE #536: Add Pending Action Button
image

### PR DESCRIPTION
**Pull request by padam11**
Capture

### CODE REVIEW

**Comment by shahdivyank** [comment]
Attach of screenshot of the visual changes

**Comment by padam11** [comment]
capture2

**Comment by SafeDuck** [comment]
Does it function properly? Meaning can you change the status of a team to "pending"?

**Comment by padam11** [comment]
Yes
capturecheck

**Review by SafeDuck — APPROVED** [review]

**Review by shahdivyank — APPROVED** [review]

**Pull request merged**
