### PR TITLE
added title to user dash board page

### LINKED ISSUE #473: Add Dashboard Title
image

- Checkout the other pages for headers/titles

### PR DESCRIPTION
**Pull request by Garman18**
Screenshot 2023-09-05 172828

### CODE REVIEW

**Review by rfairooz — CHANGES_REQUESTED** [review]
Make sure the profile header does not move to the side like that. It should be exactly like it was before just under the title dashboard this time.

**Review by rfairooz — COMMENTED** [review]
Also Change the title to "Dashboard"

**Comment by shahdivyank** [comment]
Attach issue

**Review by shahdivyank — APPROVED** [review]

**Review by rfairooz — APPROVED** [review]

**Review by rfairooz — COMMENTED** [review]
address comments. update the screenshot

**Pull request merged**
