### PR TITLE
added general logo

### LINKED ISSUE #671: Change to Generic Logo
image

- Currently uses rosehack logo, but needs to be general, maybe use Vercel logo or UCR logo

### PR DESCRIPTION
**Pull request by stormyy00**
Screenshot 2023-09-23 at 7 58 27 PM

### CODE REVIEW

**Comment by shahdivyank** [comment]
Check the description on the issue pls

**Comment by shahdivyank** [comment]
This does not solve the issue, does the rosehack logo still show up?

**Comment by stormyy00** [comment]
> This does not solve the issue, does the rosehack logo still show up?

yes it does, so you want me to change the logo in navigation..jsx?

**Comment by shahdivyank** [comment]
rosehack logo shouldn't show up , it should just be the UCR one

**Pull request closed without merging**
