### PR TITLE
add component test for Status.jsx

### LINKED ISSUE #1397: Create Status Component Test

### PR DESCRIPTION
**Pull request by lowbabun**
image

### CODE REVIEW

**Comment by lowbabun** [comment]
image

**Comment by shahdivyank** [comment]
Use Cypress

**Review by nidheesh-m-vakharia — COMMENTED** [review]
Should change the location to the cypress/component/form/ and change file name to Status.cy.jsx. As the test doesnt appear in current component tests

**Comment by lowbabun** [comment]
image
image

**Review by shahdivyank — APPROVED** [review]

**Pull request merged**
